### ISSUE TITLE
Could Not Load File or Assembly Error

### ISSUE THREAD

**Issue by yannduran** [ejensen/toggle-switch-control#1]
I'm trying to use this **excellent** control in a _UIElementDialogPage_ in a VS extension.

The project compiles fine, & at design-time I see the _ToggleSwitch_ control in the designer. However, when I run the extension in the VS Experimental instance I get the error below.

_Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll_

_Additional information: Could not load file or assembly 'ToggleSwitch_
_PublicKeyToken=8637099990568f75' or one of its dependencies. The system cannot find the file specified._

My extension targets .NET 4.6, so I tried cloning the repo and re-targeting it to 4.6, but that didn't help. It may not be the control that is at fault here, seeing as it shows fine at design-time, but I thought I'd ask anyway (just in case someone had an answer).

**Comment by curob** [comment]
I realize that this is really old, but I am having the same problem. One thing that I saw was that my application is a 64 bit application but the nuget package appears to be a 32 bit library.

This architecture difference prevented me from using this (apparently fantastic) package.

**Comment by ezekumar** [comment]
I am getting the below error 
Could not load file or assembly 'ToggleSwitch.Aero, Version=1.1.1.0, Culture=neutral, PublicKeyToken=8637099990568f75' or one of its dependencies. The system cannot find the file specified.

**Comment by angela-yan** [comment]
I am getting the following error as well:
Could not load file or assembly 'ToggleSwitch.Aero2, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by ejensen** [comment]
I believe this was fixed in https://github.com/ejensen/toggle-switch-control/pull/5 and https://github.com/ejensen/toggle-switch-control/commit/52e71d47869dfde6e6388ae27fb1526a9d6d8e04
