### ISSUE TITLE
Event handler for ToggleSwitch:HorizontalToggleSwitch

### ISSUE THREAD

**Issue by jamietansm** [ejensen/toggle-switch-control#7]
I wish to trigger an action once the button is toggled. May I check what's the event handler property to be used in the xaml code? A sample of the corresponding cs event handler code would be appreciated too.

Thank you!

**Comment by ejensen** [comment]
There is an `IsChecked` property on `HorizontalToggleSwitch` it can be used to call event handlers. There is a [section of the Demo project within this repository](https://github.com/ejensen/toggle-switch-control/blob/master/WPF/Demo/Views/Events.xaml#L22-L23) that shows how toggling the control [calls cs code](https://github.com/ejensen/toggle-switch-control/blob/master/WPF/Demo/DemoViewModel.cs#L18).
